Villas Bonaterra/Controllers/VisitorController.cs
using VillasBonaterra.Models;
using VillasBonaterra.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace VillasBonaterra.Controllers
{
    public class VisitorController : Controller
    {
        Villas_BonaterraEntities db = new Villas_BonaterraEntities();
        // GET: Visitor
        public ActionResult Index()
        {
            var datos = (from visitor in db.Visitantes select visitor).OrderBy(s => s.nombre).ThenBy(s => s.apellido1).ThenBy(s => s.apellido2).ToList();
            return View(datos);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Update(Guid id)
        {
            var Visitor = db.Visitantes.Where(x => x.id_visitante == id).FirstOrDefault();
            ViewBag.CheckedBy = Visitor.VerificacionVisitantes.Select(w => w.Usuario.nombre+ " "+ w.Usuario.apellido1 + " " + w.Usuario.apellido2).FirstOrDefault();
            return View(Visitor);
        }
    }
}

Villas Bonaterra/Views/Visitor/Add.cshtml
@{
    ViewBag.Title = "Alta de Visitante";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<title>@ViewBag.Title</title>

@section css{
    @Styles.Render("~/Assets/VisitorCSS")
}
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index", "Visitor")">Visitantes</a>
    </li>
    <li class="breadcrumb-item active">@ViewBag.Title</li>
</ol>
<hr>
<h1>@ViewBag.Title</h1>

<form id="VisitorForm" name="VisitorForm" enctype="multipart/form-data">
    <div class="form-group">
        <label for="InputName">Nombre</label>
        <input type="text" class="form-control" id="Name" aria-describedby="Name" placeholder="Escriba aqui el nombre" required>
    </div>
    <div class="form-group">
        <label for="MidleName">Primer Apellido</label>
        <input type="text" class="form-control" id="MidleName" placeholder="Escriba aqui el primer apellido" required>
    </div>
    <div class="form-group">
        <label for="LastName">Segunto Apellido</label>
        <input type="text" class="form-control" id="LastName" placeholder="Escriba aqui el segunto apellido" required>
    </div>
    <div class="form-group">
        <label for="role">Fecha Nacimiento</label>
        <div class='input-group date' id='datepicker'>
            <input type='text' class="form-control" id="BirthDate" name="BirthDate" required>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>
    <div class="form-group" id="previewform" style="display:none;">
        <img id="preview" src="" alt="Foto" height="auto" width="370px">
    </div>
    <div class="form-group">
        <label for="LastName">Foto</label>
        <input type="file" class="form-control" id="Photo" name="Photo" placeholder="Selecione la foto" onchange="readURL(this);" required>
    </div>
    <div class="alert alert-danger" id="error" style="display:none;">
        <strong id="typemessage"></strong> <span id="message"></span>
    </div>
    <button type="submit" class="btn btn-primary btn-block">Guardar</button>
</form>

@section js{
    @Scripts.Render("~/Assets/VisitorAdd")
}

Villas Bonaterra/Views/Visitor/Index.cshtml
@model IEnumerable<VillasBonaterra.Models.Visitantes>

@{
    ViewBag.Title = "Visitantes";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index", "Home")">Visitantes</a>
    </li>
    <li class="breadcrumb-item active">@ViewBag.Title</li>
</ol>
<hr>
<h1>@ViewBag.Title</h1>
<div class="card mb-3">
    <div class="card-header">
        <a class="btn btn-primary" href="/Visitor/Add">Nuevo Visitante</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTableVisitor" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>PIN</th>
                        <th>Nombre</th>
                        <th class="text-center">Foto</th>
                        <th class="text-center">Verificado</th>
                        <th class="text-center">Editar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.OrderBy(s=>s.nombre).ThenBy(s=>s.apellido1).ThenBy(s=>s.apellido2))
                    {
                    <tr>
                        <td>
                            @String.Format(item.pin)
                        </td>
                        <td>
                            @String.Format(item.nombre + " " + item.apellido1 + " " + item.apellido2)
                        </td>
                        <td class="text-center">
                            <a class="nav-link" data-toggle="modal" data-target="#CardModal" data-url="@String.Format("../Content/Photos/min" + item.foto)" style="cursor:zoom-in">
                                <i class="fa fa-fw fa-credit-card"></i>
                            </a>
                        </td>
                        <td style="text-align:center;">
                            @{ 
                                if (item.verificado) {
                                    <i class="fa fa-fw fa-check"></i>
                                }
                                else {
                                }
                            }
                        </td>
                        <td class="text-center">
                            <a href="@Url.Action("Update", "Visitor", new { id = @item.id_visitante })" visitorid="@item.id_visitante">
                                <i class="fa fa-fw fa-edit"></i>
                            </a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted"></div>
</div>
<!-- Card Modal-->
<div class="modal fade" id="CardModal" tabindex="-1" role="dialog" aria-labelledby="CardModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="LogoffModalLabel"></h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body"><img id="photo" src="" style="width: 100%; height: auto;"></div>
            <div class="modal-footer">
                <button class="btn btn-primary" type="button" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
@section js{
    @Scripts.Render("~/Assets/Visitor")
}

Villas Bonaterra/Views/Visitor/Update.cshtml
@model VillasBonaterra.Models.Visitantes

@{
    ViewBag.Title = "Editar de Visitante";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<title>@ViewBag.Title</title>

@section css{
    @Styles.Render("~/Assets/VisitorCSS")
}
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index", "Visitor")">Visitantes</a>
    </li>
    <li class="breadcrumb-item active">@ViewBag.Title</li>
</ol>
<hr>
<h1>@ViewBag.Title</h1>

<form id="VisitorUpdateForm" name="VisitorEditForm" enctype="multipart/form-data">
    <div class="form-group">
        <input value="@Model.id_visitante" type="hidden" id="Id" required>
        <label for="InputName">Nombre</label>
        <input value="@Model.nombre" type="text" class="form-control" id="Name" aria-describedby="Name" placeholder="Escriba aqui el nombre" required>
    </div>
    <div class="form-group">
        <label for="MidleName">Primer Apellido</label>
        <input value="@Model.apellido1" type="text" class="form-control" id="MidleName" placeholder="Escriba aqui el primer apellido" required>
    </div>
    <div class="form-group">
        <label for="LastName">Segunto Apellido</label>
        <input value="@Model.apellido2" type="text" class="form-control" id="LastName" placeholder="Escriba aqui el segunto apellido" required>
    </div>
    <div class="form-group">
        <label for="role">Fecha Nacimiento</label>
        <div class='input-group date' id='datepicker'>
            <input value="@Model.nacimiento.ToString("dd/MM/yyyy")" type='text' class="form-control" id="BirthDate" name="BirthDate" required>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>

    <div class="form-group">
        <label for="LastName">Identificacion</label>
        <img id="preview" src="../../Content/Photos/@Model.foto" alt="Foto" height="auto" width="370px">
    </div>
    <div class="form-group">
        <label for="LastName">Foto</label>
        <input type="file" class="form-control" id="Photo" name="Photo" placeholder="Cambiar la foto" onchange="readURL(this);">
    </div>
    @{
        if (Model.verificado)
        {
            <label class="container" style="float:left;">
                Verificado por: @ViewBag.CheckedBy
                <span class="checkmark" style="background-color: #2196F3; text-align:center;"><i class="fa fa-check" style="color:white;"></i></span>
            </label>
        }
        else
        {
            <label class="container" style="float:left;">
                Verificar
                @Html.CheckBoxFor(model => model.verificado)
                <span class="checkmark"></span>
            </label>
        }
    }
    <div class="form-group" style="clear: both;">
        <div class="alert alert-danger" id="error" style="display:none; text-align:center !important;">
            <strong id="typemessage"></strong> <span id="message"></span>
        </div>
    </div>
        <button type="submit" class="btn btn-primary btn-block">Guardar</button>
</form>

@section js{
    @Scripts.Render("~/Assets/VisitorAdd")
}