Villas Bonaterra/ViewModels/StreetViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VillasBonaterra.ViewModels
{
    public class StreetViewModel
    {
        [Required]
        [Display(Name = "Id")]
        public Guid Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Numbers")]
        public string Numbers { get; set; }
    }
}

Villas Bonaterra/Controllers/StreetController.cs
using VillasBonaterra.Models;
using VillasBonaterra.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static VillasBonaterra.ApiControllers.StreetController;

namespace VillasBonaterra.Controllers
{
    public class StreetController : Controller
    {
        Villas_BonaterraEntities db = new Villas_BonaterraEntities();
        // GET: Street
        public ActionResult Index()
        {
            List<StreetViewModel> streets = new List<StreetViewModel>();
            List<StreetViewModel> streetsView = new List<StreetViewModel>();

            streets = (from street in db.Calles from address in db.Domicilios where address.id_calle==street.id_calle orderby street.nombre ascending select new StreetViewModel { Id = street.id_calle, Name = street.nombre, Numbers = address.no_casa }).ToList();

            //var result = streets.GroupBy(cc => cc.Name).Select(dd => new { Name = dd.Key, Id = dd.Select(w => w.Id).FirstOrDefault(), Numbers = string.Join(",", dd.Select(ee => ee.Numbers).ToList())}).ToList();
              var result = streets.GroupBy(cc => cc.Name).Select(dd => new { Name = dd.Key, Id = dd.Select(w => w.Id).FirstOrDefault(), Numbers = string.Join(",", dd.Select(ee => ee.Numbers).OrderBy(g => g).ToList())}).ToList();
            streetsView = result.Select(s => new StreetViewModel { Id = s.Id, Name = s.Name, Numbers = s.Numbers }).ToList();
            
            return View(streetsView);
        }
    }
}

Villas Bonaterra/Views/Street/Index.cshtml
@{
        ViewBag.Title = "Lista de Calles";
        Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="@Url.Action("Index", "Street")">Calles</a>
        </li>
        <li class="breadcrumb-item active">@ViewBag.Title</li>
    </ol>
    <hr>
    <h1>@ViewBag.Title</h1>
    <div class="card mb-3">
        <div class="card-header">
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Casas</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td style="max-width:100px; width:200px;">
                                    @item.Name
                                </td>
                                <td style="max-width:150px;">
                                    @item.Numbers
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer small text-muted"></div>
    </div>
    <!-- Card Modal-->
    <div class="modal fade" id="CardModal" tabindex="-1" role="dialog" aria-labelledby="CardModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="LogoffModalLabel"></h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body"><img id="photo" src="" style="width: 100%; height: auto;"></div>
                <div class="modal-footer">
                    <button class="btn btn-primary" type="button" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    @section js{
        @Scripts.Render("~/Assets/Visitor")
    }